import React,{useLayoutEffect,useMemo,useRef} from 'react';
import * as THREE from 'three';
import {useSolPbrTextures} from '../materials/useSolPbrTextures';
import {getTerrainHeight,type RockData,type RockVariant} from './forest/RockData';
import {ROCK_SET_A} from './forest/rockSetA';import {ROCK_SET_B1} from './forest/rockSetB1';import {ROCK_SET_B2} from './forest/rockSetB2';import {ROCK_SET_C} from './forest/rockSetC';import {ROCK_SET_D} from './forest/rockSetD';import {createRockGeometries} from './forest/RockGeometry';
export {getTerrainHeight} from './forest/RockData';
const ITEMS=[...ROCK_SET_A,...ROCK_SET_B1,...ROCK_SET_B2,...ROCK_SET_C,...ROCK_SET_D];const SHADOWED=new Set<RockVariant>(['LARGE_A','LARGE_B','ROCK_B']);
const Instances:React.FC<{geometry:THREE.BufferGeometry;material:THREE.Material;items:RockData[];cast:boolean}>=({geometry,material,items,cast})=>{const ref=useRef<THREE.InstancedMesh>(null!);useLayoutEffect(()=>{if(!geometry.boundingBox)geometry.computeBoundingBox();const box=geometry.boundingBox!,minY=box.min.y,height=box.max.y-box.min.y,dummy=new THREE.Object3D();items.forEach((item,index)=>{const[x,z]=item.position,[sx,sy,sz]=item.scale,[rx,ry,rz]=item.rotation;const y=getTerrainHeight(x,z)-height*sy*item.embedRatio-minY*sy;dummy.position.set(x,y,z);dummy.rotation.set(rx,ry,rz);dummy.scale.set(sx,sy,sz);dummy.updateMatrix();ref.current.setMatrixAt(index,dummy.matrix);});ref.current.instanceMatrix.needsUpdate=true;},[geometry,items]);return <instancedMesh ref={ref} args={[geometry,material,items.length]} castShadow={cast} receiveShadow/>;};
export const RocksLayer:React.FC<{wireframeMode?:boolean}>=({wireframeMode=false})=>{const geometries=useMemo(createRockGeometries,[]);const groups=useMemo(()=>{const result:Record<RockVariant,RockData[]>={ROCK_A:[],ROCK_B:[],ROCK_C:[],LARGE_A:[],LARGE_B:[]};ITEMS.forEach(item=>result[item.variant].push(item));return result;},[]);const pbr=useSolPbrTextures('02_dark_wet_rock',[.4,.4]);const scale=useMemo(()=>new THREE.Vector2(.35,.35),[]);const material=useMemo(()=>new THREE.MeshStandardMaterial({map:pbr.map,normalMap:pbr.normalMap,normalScale:scale,roughnessMap:pbr.roughnessMap,roughness:.62,metalness:0,wireframe:wireframeMode}),[pbr.map,pbr.normalMap,pbr.roughnessMap,scale,wireframeMode]);return <group name="Environment_Rock_Layer">{(Object.keys(groups) as RockVariant[]).map(v=><Instances key={v} geometry={geometries[v]} material={material} items={groups[v]} cast={SHADOWED.has(v)}/>)}</group>;};
