import {useMemo} from 'react';
import * as THREE from 'three';
const cache=new Map<string,THREE.Texture>();
type Channel='basecolor'|'normal'|'roughness';
const palettes:Record<string,{base:[number,number,number];roughness:number}>={'01_forest_ground':{base:[38,48,42],roughness:.87},'02_dark_wet_rock':{base:[42,45,45],roughness:.62},'03_conifer_bark':{base:[48,35,27],roughness:.78},'04_charcoal_facade':{base:[35,39,40],roughness:.76},'05_dark_roof':{base:[35,39,41],roughness:.72},'06_moss':{base:[42,67,47],roughness:.90}};
function hashString(input:string){let hash=2166136261;for(let i=0;i<input.length;i++){hash^=input.charCodeAt(i);hash=Math.imul(hash,16777619);}return hash>>>0;}
function randomFactory(seed:number){let state=seed||1;return()=>{state^=state<<13;state^=state>>>17;state^=state<<5;return(state>>>0)/4294967295;};}
function createTexture(folder:string,channel:Channel,repeat:[number,number]):THREE.Texture{const size=128,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw new Error('Unable to create material canvas');const image=ctx.createImageData(size,size),data=image.data,palette=palettes[folder]??{base:[64,64,64] as [number,number,number],roughness:.8},rnd=randomFactory(hashString(`${folder}:${channel}`));for(let y=0;y<size;y++){for(let x=0;x<size;x++){const i=(y*size+x)*4,fine=rnd()-.5,broad=Math.sin(x*.11+y*.07)*.5+Math.cos(x*.035-y*.045)*.5,bark=folder==='03_conifer_bark'?Math.sin(x*.55)*.7:0,roof=folder==='05_dark_roof'?Math.sin((x+y)*.08)*.25:0,variation=fine*18+broad*7+bark*6+roof*4;if(channel==='basecolor'){data[i]=THREE.MathUtils.clamp(palette.base[0]+variation,0,255);data[i+1]=THREE.MathUtils.clamp(palette.base[1]+variation,0,255);data[i+2]=THREE.MathUtils.clamp(palette.base[2]+variation,0,255);}else if(channel==='normal'){const a=folder==='03_conifer_bark'?9:folder==='02_dark_wet_rock'?7:3;data[i]=THREE.MathUtils.clamp(128+fine*a+bark*a,0,255);data[i+1]=THREE.MathUtils.clamp(128+broad*a,0,255);data[i+2]=250;}else{const value=THREE.MathUtils.clamp(palette.roughness*255+fine*14+broad*7,0,255);data[i]=value;data[i+1]=value;data[i+2]=value;}data[i+3]=255;}}ctx.putImageData(image,0,0);const texture=new THREE.CanvasTexture(canvas);texture.wrapS=THREE.RepeatWrapping;texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(...repeat);texture.colorSpace=channel==='basecolor'?THREE.SRGBColorSpace:THREE.NoColorSpace;texture.anisotropy=4;texture.needsUpdate=true;return texture;}
function getTexture(folder:string,channel:Channel,repeat:[number,number]){const key=`${folder}:${channel}?r=${repeat[0]},${repeat[1]}`,hit=cache.get(key);if(hit)return hit;const t=createTexture(folder,channel,repeat);cache.set(key,t);return t;}
export type PbrRepeatOption=[number,number]|{baseColor?:[number,number];normal?:[number,number];roughness?:[number,number]};
export interface PbrConfigOptions{repeat:PbrRepeatOption;enableNormal?:boolean;enableRoughness?:boolean;}
export function useSolPbrTextures(folder:string,options:PbrRepeatOption|PbrConfigOptions){const config=useMemo(()=>{if(typeof options==='object'&&options!==null&&'repeat' in options){const cfg=options as PbrConfigOptions;return{repeat:cfg.repeat,enableNormal:cfg.enableNormal??true,enableRoughness:cfg.enableRoughness??true};}return{repeat:options as PbrRepeatOption,enableNormal:true,enableRoughness:true};},[options]);const resolve=(channel:'baseColor'|'normal'|'roughness'):[number,number]=>Array.isArray(config.repeat)?config.repeat:config.repeat[channel]??[1,1];const bc=resolve('baseColor'),nr=resolve('normal'),rr=resolve('roughness');const map=useMemo(()=>getTexture(folder,'basecolor',bc),[folder,bc[0],bc[1]]);const normalMap=useMemo(()=>config.enableNormal?getTexture(folder,'normal',nr):null,[folder,config.enableNormal,nr[0],nr[1]]);const roughnessMap=useMemo(()=>config.enableRoughness?getTexture(folder,'roughness',rr):null,[folder,config.enableRoughness,rr[0],rr[1]]);return{map,normalMap,roughnessMap};}
